### ISSUE TITLE
Cannot run nix-shell

### ISSUE THREAD

**Issue by SebGGruber** [devmotion/Calibration_ICLR2021#5]
Hi,

I tried to follow your install instructions, installing `nix` and running `nix-shell`, but it gives me `error: getting status of '.../Calibration_ICLR2021/default.nix': No such file or directory`.
Any suggestions how to deal with this? I could not find such a file in this repository.

Greetings,
Sebastian

**Comment by devmotion** [comment]
Sorry for the slow response, somehow I lost track of this issue in my backlog.

It seems you ran `nix-shell` in the main directory of the repository? You have to navigate to the respective folder (e.g., `experiments`) first and run `nix-shell` in the subfolder (it's mentioned briefly in e.g. https://github.com/devmotion/Calibration_ICLR2021/blob/main/experiments/README.md but perhaps not clearly enough).

I just checked out the repo locally, navigated to `experiments`, and ran `nix-shell`. That seemed to work.

**Comment by SebGGruber** [comment]
Hi,
I thought I tried this out, but it appears I somehow missed it.
It now worked, thanks a lot!
